#ifndef FILEMANAGERGLOBAL_H
#define FILEMANAGERGLOBAL_H

#include <QtGlobal>

#if defined(FILEMANAGER_BUILD_LIBRARY)
#define FILEMANAGER_EXPORT Q_DECL_EXPORT
#else
#define FILEMANAGER_EXPORT Q_DECL_IMPORT
#endif

#endif // FILEMANAGERGLOBAL_H
